### ISSUE TITLE
Checking for contradiction when comparing conditions

### ISSUE THREAD

**Issue by mudbri** [ravel-net/pyotr#12]
When checking if the head is contained within the generated DB, we first compare the data part of tuples with the head and if a tuple matches the head, we check if the condition associated with the tuple implies the condition of the head. However, we do not check if the condition of the tuple is a contradiction or not. If it is a contradiction, then implication will always be true. Thus, we need to either remove tuples with contradictions earlier on OR check for contradiction [here](https://github.com/ravel-net/pyotr/blob/6bdbbbc9d7b6322a47a235d98e680fbac493bc28/Core/Homomorphism/Datalog/rule.py#L458)

**Comment by mudbri** [comment]
A fix would be to change [this](https://github.com/ravel-net/pyotr/blob/6bdbbbc9d7b6322a47a235d98e680fbac493bc28/Core/Homomorphism/Datalog/rule.py#L458) line to:
`if not self.z3tools.iscontradiction(str_tup_cond) and self.z3tools.is_implication(str_tup_cond, header_condition):`

However, this is currently giving an error

**Comment by lanfangping** [comment]
> A fix would be to change [this](https://github.com/ravel-net/pyotr/blob/6bdbbbc9d7b6322a47a235d98e680fbac493bc28/Core/Homomorphism/Datalog/rule.py#L458) line to: `if not self.z3tools.iscontradiction(str_tup_cond) and self.z3tools.is_implication(str_tup_cond, header_condition):`
> 
> However, this is currently giving an error

The input of `z3tools.iscontradiction()` is a list of string conditions. Thus, `self.z3tools.iscontradiction([str_tup_cond])` should be correct.

**Comment by mudbri** [comment]
Thanks, this fixed the problem!
