### ISSUE TITLE
Problem with merge_tuples

### ISSUE THREAD

**Issue by mudbri** [ravel-net/pyotr#19]
The output of minimizing some programs is different when simplification is on vs when simplification is not on. This should not occur, since simplification is just an optimization. Specifically, the output of minimizing the following program is different:
 ```
p1 = "R(a3, h3, [h3], 1)[h3 = 10] :- l(a3,h3)[h3 = 10], l(a3,e1)\nR(a2, h3, [h3], 1) :- l(a2,h3), l(a2, h4), l(a2, e1)\nR(e1, h3, [a2, x], 2) :- R(a2, h3, [x], 1), l(a2, e1), l(a1, e1), l(a3, e1)"
program1 = DT_Program(p1, {"R":["int4_faure", "int4_faure","int4_faure[]", "integer"], "l":["int4_faure", "int4_faure"]}, domains={'h3':['10', '20']}, c_variables=['h3'], reasoning_engine='z3', reasoning_type='Int', datatype='int4_faure', simplification_on=True, c_tables=["R", "l"])
start = time.time()
program1.minimize()
print(program1)
```
The output is different when `simplification_on=False`.

I debugged this problem, and found that the real problem is in merge_tuples. Specifically, when the program above checks if rule `Checking  R(a2,h3,[h3],1) :- l(a2,h3),l(a2,e1)` is contained within the original program, there are discrepancies in output after line [549](https://github.com/ravel-net/pyotr/blob/d5f7bc800f85b0a145b669b4a1f9aabd2bef48af/Core/Homomorphism/Datalog/rule.py#L544). For reference, I am providing the result of merge tuples when simplification is off:

Before line 549 the head is:
```
test=# select * from R;
 c0  | c1  |  c2   | c3 |            condition            
-----+-----+-------+----+---------------------------------
 100 | h3  | {h3}  |  1 | {"h3 == 10"}
 100 | h3  | {h3}  |  1 | {"And(100 == 100, 100 == 100)"}
 100 | h3  | {h3}  |  1 | {"And(100 == 100, 100 == 100)"}
 100 | h3  | {h3}  |  1 | {"And(100 == 100, 100 == 100)"}
 100 | h3  | {h3}  |  1 | {"And(100 == 100, 100 == 100)"}
 100 | 101 | {101} |  1 | {"And(100 == 100, 100 == 100)"}
 100 | 101 | {101} |  1 | {"And(100 == 100, 100 == 100)"}
 100 | 101 | {101} |  1 | {"And(100 == 100, 100 == 100)"}
 100 | 101 | {101} |  1 | {"And(100 == 100, 100 == 100)"}
```
But after line 549, the head is:
```
test=# select * from R;
 c0  | c1  |  c2   | c3 | condition 
-----+-----+-------+----+-----------
 100 | h3  | {h3}  |  1 | {}
 100 | 101 | {101} |  1 | {}
```

All conditions are removed, even though they should not be. If simplification is on, the result looks something like this:

Before line 549 the head is:
```
test=# select * from R;
 c0  | c1  |  c2   | c3 |  condition   
-----+-----+-------+----+--------------
 100 | h3  | {h3}  |  1 | {"h3 == 10"}
 100 | h3  | {h3}  |  1 | {}
 100 | h3  | {h3}  |  1 | {}
 100 | h3  | {h3}  |  1 | {}
 100 | h3  | {h3}  |  1 | {}
 100 | 101 | {101} |  1 | {}
 100 | 101 | {101} |  1 | {}
 100 | 101 | {101} |  1 | {}
 100 | 101 | {101} |  1 | {}
```
But after line 549, the head is:
```
test=# select * from R;
 c0  | c1  |  c2   | c3 |  condition   
-----+-----+-------+----+--------------
 100 | h3  | {h3}  |  1 | {"h3 == 10"}
 100 | 101 | {101} |  1 | {}
```

Notice how the condition {"h3 == 10"} is preserved when simplification is on

**Comment by lanfangping** [comment]
Thank you for pointing them out. They should be fixed in commit 6d49553bc68e2578bb34a12799787ffd2586267e. I made some changes in simplification before but did not fully test it. Let me know if there are still bugs.

**Comment by mudbri** [comment]
When running unit_tests, I get the following error:
```
Traceback (most recent call last):
  File "unit_tests.py", line 43, in <module>
    program1.minimize()
  File "/home/mudbri/Documents/GitHub/pyotr/Core/Homomorphism/Datalog/program.py", line 151, in minimize
    contained = self.contains_rule(rule_with_deleted_atom)
  File "/home/mudbri/Documents/GitHub/pyotr/Core/Homomorphism/Datalog/program.py", line 112, in contains_rule
    changed = self.execute(conn)
  File "/home/mudbri/Documents/GitHub/pyotr/Core/Homomorphism/Datalog/program.py", line 74, in execute
    DB_changes = rule.execute(conn)
  File "/home/mudbri/Documents/GitHub/pyotr/Core/Homomorphism/Datalog/rule.py", line 326, in execute
    return self.run_with_faure(conn, self.sql)
  File "/home/mudbri/Documents/GitHub/pyotr/Core/Homomorphism/Datalog/rule.py", line 577, in run_with_faure
    changed = self.insertTuplesToHead(conn)
  File "/home/mudbri/Documents/GitHub/pyotr/Core/Homomorphism/Datalog/rule.py", line 543, in insertTuplesToHead
    merge_tuples_z3.merge_tuples(header_table, # tablename of header
TypeError: merge_tuples() got an unexpected keyword argument 'simplification_on'
```

**Comment by lanfangping** [comment]
Sorry! the `merge_tuples()` function was missed when I committed the changes. I commit it in 1daa0708129bfc18727ddc9e2208fa3cb4ae21d2, now it should be good.

**Comment by mudbri** [comment]
Thank you @lanfangping! It's working now. However, would it be possible for you to briefly describe what the problem and the fix was? I don't understand which result was correct (the one with simplification or the one without). Just wanna make sure that we are implementing the correct thing. Thanks!

**Comment by mudbri** [comment]
Also, a quick (but important) observation: the execution is much faster when simplification is off. This is something we might want to look into in the future

**Comment by lanfangping** [comment]
The one without simplification is correct. 

Before simplifying
```
 c0  | c1  |  c2   | c3 |            condition            
-----+-----+-------+----+---------------------------------
 100 | h3  | {h3}  |  1 | {"h3 == 10"}
 100 | h3  | {h3}  |  1 | {"And(100 == 100, 100 == 100)"}
 100 | h3  | {h3}  |  1 | {"And(100 == 100, 100 == 100)"}
 100 | h3  | {h3}  |  1 | {"And(100 == 100, 100 == 100)"}
 100 | h3  | {h3}  |  1 | {"And(100 == 100, 100 == 100)"}
```

Simplified
```
 c0  | c1  |  c2   | c3 |  condition   
-----+-----+-------+----+--------------
 100 | h3  | {h3}  |  1 | {"h3 == 10"}
 100 | h3  | {h3}  |  1 | {}
 100 | h3  | {h3}  |  1 | {}
 100 | h3  | {h3}  |  1 | {}
 100 | h3  | {h3}  |  1 | {}
```

When simplification is on, the condition of the above rows except the first row should be `"{}"` which is a tautology. The bug happens in merging tautological conditions. **If the condition is empty(tautology), the code does not add a `True` to the condition list, i.e., adding nothing to the condition list**. For example, the condition list of the simplified rows should be `"{h3 == 10, True, True, True, True}"` then do logical OR-ing for this condition list. `Or(h3 == 10, True, True, True, True)` is obviously a tautology. So the result of merging is `100 | h3  | {h3}  |  1 | {}`. However, when adding nothing, the condition list only contains `h3 == 10`, so the merged result of the condition is `{h3 == 10}` which would be preserved in the condition column.



When simplification is off, every row does not have an empty condition, so the bug was not triggered. 

My solution is instead of adding a `True` to the condition list for a row, once I found an empty condition when merging, I directly set this row with a tautological condition(i.e., empty condition) without reasoning, because logical OR-ing a tautology always returns True. Thus, we can improve some performance here. Does this make sense to you?

**Comment by mudbri** [comment]
Makes sense. Thanks for the explanation!
