### ISSUE TITLE
Whole Integer Set Issue in BDD

### ISSUE THREAD

**Issue by mudbri** [ravel-net/pyotr#21]
Issue pointed out by Fangping: I found an issue with the c-variables for BDD.  For [unit_test 3](https://urldefense.com/v3/__https://github.com/ravel-net/pyotr/blob/homomorphism/Core/Homomorphism/Datalog/unit_tests.py*L39__;Iw!!DZ3fjg!4l73IikQ1cWihWkfdHwNpSBUywCC3xEUuQoCrniMlbePkoWivAvspBNLYer_mgCjoCxmarHbCDF1oObgq7fOhdhBkPg$), we set the domain of c-variable h3 with ['10', '20'], but when we check if the head is in the results, the extra conditions would have some constraints such as 'h3 == 101' that 101 is out of the domain. Thus the encodeCUDD reports an error as the following shows. I think we need to check if the compared value is out of the domain, if not, it is a contradictory BDD. By the way, if I remember correctly, our BDD implementation must set domains for c-variables. What should we set the domain for the whole integer sets? Z3 Solver is using the whole integer sets as the domain for c-variables as default. What should BDD do? 

Traceback (most recent call last):
  File "/home/fangping/Projects/pyotr/Core/Homomorphism/Datalog/unit_tests.py", line 43, in <module>
    program1.minimize()
  File "/home/fangping/Projects/pyotr/Core/Homomorphism/Datalog/program.py", line 267, in minimize
    minimizeAtoms(self)
  File "/home/fangping/Projects/pyotr/Core/Homomorphism/Datalog/DL_minimization.py", line 19, in minimizeAtoms
    contained = P.contains_rule(rule_with_deleted_atom)
  File "/home/fangping/Projects/pyotr/Core/Homomorphism/Datalog/program.py", line 235, in contains_rule
    if rule2.isHeadContained(conn):
  File "/home/fangping/Projects/pyotr/Core/Homomorphism/Datalog/rule.py", line 354, in isHeadContained
    return self.is_head_contained_faure(conn)
  File "/home/fangping/Projects/pyotr/Core/Homomorphism/Datalog/rule.py", line 520, in is_head_contained_faure
    extra_condition_idx = self.reasoning_tool.str_to_BDD(extra_conditions)
  File "/home/fangping/Projects/pyotr/Backend/reasoning/CUDD/BDDTools.py", line 30, in str_to_BDD
    encoded_c, variablesArray = encodeCUDD.convertToCUDD(condition, self.domain_list, self.variables, self._is_IP)
  File "/home/fangping/Projects/pyotr/Backend/reasoning/CUDD/BDD_manager/encodeCUDD.py", line 186, in convertToCUDD
    encodedCond = processCon(splitConditions[0], splitConditions[1], input_domain, is_ip)
  File "/home/fangping/Projects/pyotr/Backend/reasoning/CUDD/BDD_manager/encodeCUDD.py", line 104, in processCon
    binary_rep = bin(updatedDomains.index(newVar2))[2:]
ValueError: '101' is not in list

**Comment by mudbri** [comment]
This should be fixed in commit 8ba194ba0510676fc50acaeba6f2b8028b0cb906. The commit has made two changes to the API:

1. *domain* is now a dictionary in ***convertToCUDD(condition, domain, variables, is_ip)***: The domain variable is a dictionary with the variable as the key and the domain of that variable as the domain. If the domain for a variable is not specified, its domain is considered to be the integer set. For example, for variables x and y where x has domain [1,2] and y has the integer set as domain, *domain* should be *{'x':['1','2']}*
2. *initialize* function in BDD now takes only one parameter: *void initialize(int numberOfVariables, int domainCardinality)* has been changed to *void initialize(int numberOfBDDVariables)*, where numberOfBDDVariables correspond to the number of variables required in BDD for representation. This parameter is returned as the second element in *convertToCUDD*.

@lanfangping, please see [test.py](https://github.com/ravel-net/pyotr/blob/8ba194ba0510676fc50acaeba6f2b8028b0cb906/Backend/reasoning/CUDD/BDD_manager/test.py#L94) for details.  I am closing the issue for now, but if there are any new problems, feel free to open the issue and comment.

**Comment by lanfangping** [comment]
Can initialize()  be used before convertToCUDD()? I see the second returned element of convertToCUDD() is different from the input variables. I created [BDDTools class](https://github.com/ravel-net/pyotr/blob/8ba194ba0510676fc50acaeba6f2b8028b0cb906/Backend/reasoning/CUDD/BDDTools.py#L11) for all BDD functions, so I am thinking that doing initialization first and then calling convertToCUDD() for conditions makes more sense. Is it possible to do that?

**Comment by mudbri** [comment]
Yes, initialize() can be called before convertToCUDD(). The input to initialize is the number of variables a BDD has to have. The number of variables in BDD is a function of the number of variables in the program and the domain of those variables. For example, consider two variables in a program, x and y, with domain {1,2,3,4} and {5,6} respectively. In BDD, the domain of x can be represented by two bits (since 2^2=4, which is the cardinality of the domain of x). Similarly, the domain of y can be represented by a single bit. Thus, the input to initialize should be 3 (i.e. 2+1). Does that make sense? The second return value if convertToCUDD simple performs this calculation using the variables and their domain.

To give input to initialize, you can compute the number of variables in BDD for a particular program manually and then use that as the argument to initialize

**Comment by lanfangping** [comment]
Hi Mubashir @mudbri, I found a memory issue when the domain of c-variables is the whole integer set.  the [test.py](https://github.com/ravel-net/pyotr/blob/homomorphism/Backend/reasoning/CUDD/BDD_manager/test.py#L108) shows an example,  there are 4 c-variables and their domain is the whole integer set, for a short condition, the str_to_BDD() cannot run to complete that the program was killed due to out-of-memory. Can this problem be solved? I think the issue makes sense to me because the whole integer set domain makes the tree complicated enough. But I was surprised there is a memory for such a short condition.

**Comment by mudbri** [comment]
Hi Fangping, this should not be giving an out-of-memory error for just four variables. There might be some issue in my code. I'll look into this

**Comment by mudbri** [comment]
@lanfangping this should be fixed in commit b582d854fe355bd858a632dc5f41e459ff8e06b2. I had to enable BDD reordering to prevent the memory blowup. Please let me know if there are still any problems

p.s. I still don't understand why reordering makes such a big difference, but apparently it does. My code for BDD and encodeCUDD is very bad and hard for even me to understand at this point. I went down a rabbit hole of debugging the recursive calls for BDD construction and at the end the fix was simply turning on reordering. Anyway, I will try to rewrite the entire code from scratch after the deadline.

**Comment by lanfangping** [comment]
Thanks! It's working right now.

**Comment by lanfangping** [comment]
> For [unit_test 3](https://urldefense.com/v3/__https://github.com/ravel-net/pyotr/blob/homomorphism/Core/Homomorphism/Datalog/unit_tests.py*L39__;Iw!!DZ3fjg!4l73IikQ1cWihWkfdHwNpSBUywCC3xEUuQoCrniMlbePkoWivAvspBNLYer_mgCjoCxmarHbCDF1oObgq7fOhdhBkPg$), we set the domain of c-variable h3 with ['10', '20'], but when we check if the head is in the results, the extra conditions would have some constraints such as 'h3 == 101' that 101 is out of the domain. Thus the encodeCUDD reports an error as the following shows. I think we need to check if the compared value is out of the domain, if not, it is a contradictory BDD.

Hi Mubashir, I modified the [processCon()](https://github.com/ravel-net/pyotr/blob/homomorphism/Backend/reasoning/CUDD/BDD_manager/encodeCUDD.py#L101) that when case "var == constant", first check if constant is in the domain, if not, return the FALSE for this condition. I checked in Z3 that the variable is set to a constant which is out of the domain, it's a contradiction.  

By the way, I also found a bug in [line 83](https://github.com/ravel-net/pyotr/commit/d2825810958a8d6a994133990b1ce9689e530c2e#diff-5721e856d1af7a4b771f73f373d1c57ac15134606e4291a99965d4d710bdb44aL83). When the condition is "constant == var", the varDomain would be empty. So, we should call preprocessCond(var1, var2) first to exchange the position of two operands then check the domain for newVar1.

**Comment by mudbri** [comment]
Thank you, Fangping! Your changes make sense to me
However, the unit tests are failing with your new commit. I see that you have added a new parameter to program.py and rule.py called reasoning tools, which might be causing this issue. How is reasoning_tools different from the parameter reasoning_engine?

**Comment by lanfangping** [comment]
> How is reasoning_tools different from the parameter reasoning_engine?

Hi Mubashir, reasoning_tools is an instance of [z3SMTTools](https://github.com/ravel-net/pyotr/blob/homomorphism/Backend/reasoning/Z3/z3smt.py#L8) or [BDDTools](https://github.com/ravel-net/pyotr/blob/homomorphism/Backend/reasoning/CUDD/BDDTools.py#L9), but reasoning_engine is just a label showing the type of reasoning_tools, 'z3' or 'bdd'. I make the instance of reasoning tools as a parameter in DT_program. This is because after several iterations, evaluating a BDD index does not work and reports errors. I  guessed the error is due to that every time the BDD module was called in DT_rule, the BDD_array would refresh and lose the information of previous BDD indexes which caused an error. After I make changes (add reasoning_tools parameter in DT_program), the error disappears.

P.S., I am thinking that if the 'reasoning_engine', 'reasoning_type', ... are redundant after adding 'reasoning_tools'. I will clean up the code after submission.

**Comment by mudbri** [comment]
Hi @lanfangping, I changed the code so that the reasoning_tools is initialized in program.py: 7fc98283c4dd17b1de9f5bf7c55e8654035d2e38. This makes sure that the user does not have to take care of the initialization. Does this make sense?

Also, I noticed that BDD is failing unit_tests 7 and 8 here: https://github.com/ravel-net/pyotr/blob/e90daeca375d3cf594478a053d0400d5bda65fad/tests/unit_tests.py#L108. (Note that theses tests were failing even before my latest commit e90daeca375d3cf594478a053d0400d5bda65fad.) Do you know why that is?

**Comment by lanfangping** [comment]
The changes make sense to me.

> Also, I noticed that BDD is failing unit_tests 7 and 8 here:
> 
> https://github.com/ravel-net/pyotr/blob/e90daeca375d3cf594478a053d0400d5bda65fad/tests/unit_tests.py#L108
> 
> . (Note that theses tests were failing even before my latest commit [e90daec](https://github.com/ravel-net/pyotr/commit/e90daeca375d3cf594478a053d0400d5bda65fad).) Do you know why that is?

They passed on my side both before and after the commit  https://github.com/ravel-net/pyotr/commit/e90daeca375d3cf594478a053d0400d5bda65fad. Let me double-check the code.

**Comment by mudbri** [comment]
There are still issues with unit tests in BDD but the integer set issue has been fixed. Closing this issue for now.
